/**
 * /init — scan the current project and generate/merge a compact, useful
 * project context file (AGENTS.md). Never clobbers user edits: an existing
 * AGENTS.md that Porcupine did not write is merged conservatively (missing
 * sections only); an existing AGENTS.md that Porcupine already generated is
 * left untouched unless /init --force is passed.
 */

import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

export const PROJECT_CONTEXT_FILE = "AGENTS.md";
export const GENERATED_HEADER = "<!-- @generated by Porcupine /init — project context. Do not edit the header. -->";

export type InitCommand = { kind: "generate"; force: boolean } | { kind: "invalid"; message: string };

export function parseInitCommand(text: string): InitCommand | null {
	const match = /^\/init(?:\s+(.*))?\s*$/i.exec(text.trim());
	if (!match) return null;
	const args = match[1]?.trim() ?? "";
	if (args && args !== "--force") {
		return { kind: "invalid", message: "Usage: /init [--force]" };
	}
	return { kind: "generate", force: args === "--force" };
}

export interface ProjectSummary {
	purpose: string;
	commands: string[];
	conventions: string[];
	stack: string[];
	topLevel: string[];
}

const SENSIBLE_DEFAULTS = {
	commands: [
		"Need actual package.json scripts? None detected at the top level.",
		"Run tests with the package manager's test script when present.",
	],
	conventions: [
		"Prefer minimal diffs; do not reformat or restructure existing code.",
		"Run targeted tests on anything touched before finishing.",
	],
} as const;

function readIfExists(path: string): string | undefined {
	try {
		return readFileSync(path, "utf8");
	} catch {
		return undefined;
	}
}

function packageJsonSummary(cwd: string): { scripts: string[]; name?: string } {
	const parsed = (() => {
		try {
			return JSON.parse(readIfExists(join(cwd, "package.json")) ?? "") as {
				name?: string;
				scripts?: Record<string, string>;
			};
		} catch {
			return { scripts: undefined };
		}
	})();
	const commands: string[] = [];
	if (parsed.scripts && typeof parsed.scripts === "object") {
		const keys = Object.keys(parsed.scripts);
		for (const key of keys.slice(0, 8)) {
			commands.push(`- \`${key}\`: \`${parsed.scripts[key]}\``);
		}
	}
	return { scripts: commands, name: parsed.name };
}

function readmeFirstLines(cwd: string): string {
	const candidate = readIfExists(join(cwd, "README.md")) ?? readIfExists(join(cwd, "Readme.md"));
	if (!candidate) return "No README found at the project root.";
	return candidate
		.split("\n")
		.filter((line) => line.trim())
		.slice(0, 3)
		.join("\n");
}

/** Scan the project and build a compact summary (pure — no file writes). */
export function buildProjectSummary(cwd: string): ProjectSummary {
	const topLevel = readdirSync(cwd)
		.filter((entry) => {
			if (entry === PROJECT_CONTEXT_FILE || entry.startsWith(".") || entry === "node_modules") return false;
			return true;
		})
		.slice(0, 24);

	const pkg = packageJsonSummary(cwd);
	const readme = readmeFirstLines(cwd);

	const stack: string[] = [];
	if (pkg.name) stack.push(`Node.js package: \`${pkg.name}\``);
	if (readIfExists(join(cwd, "packages"))) stack.push("Monorepo with a packages/ workspace.");
	if (readIfExists(join(cwd, "tsconfig.json"))) stack.push("TypeScript (tsconfig.json present).");
	if (readIfExists(join(cwd, "vitest.config.ts"))) stack.push("Vitest configured.");
	if (stack.length === 0) stack.push("Generic project — no recognized toolchain markers at the root.");

	return {
		purpose: readme.split("\n")[0] ?? "Project purpose: see README.",
		commands: pkg.scripts.length ? pkg.scripts : [...SENSIBLE_DEFAULTS.commands],
		conventions: [...SENSIBLE_DEFAULTS.conventions],
		stack,
		topLevel,
	};
}

/** Build the full generated AGENTS.md content for a project summary. */
export function renderProjectContext(summary: ProjectSummary): string {
	const lines: string[] = [
		GENERATED_HEADER,
		"",
		`# ${PROJECT_CONTEXT_FILE}`,
		"",
		"Auto-generated project context for the Porcupine agent.",
		"",
		"## Purpose",
		"",
		summary.purpose,
		"",
		"## Key Commands",
		"",
		...summary.commands.map((line) => `- ${line}`),
		"",
		"## Conventions",
		"",
		...summary.conventions.map((line) => (line.startsWith("- ") ? line : `- ${line}`)),
		"",
		"## Stack",
		"",
		...summary.stack.map((line) => `- ${line}`),
		"",
		"## Top-level layout",
		"",
		summary.topLevel.map((entry) => `- ${entry}/`).join("\n"),
		"",
	];
	return lines.join("\n");
}

export interface InitResult {
	status: "created" | "unchanged" | "merged" | "already-generated" | "error";
	path: string;
	content?: string;
	message?: string;
}

/** Split the generated doc into section names so the merge can add missing ones. */
function sectionNames(content: string): string[] {
	const names: string[] = [];
	for (const line of content.split("\n")) {
		if (line.startsWith("## ")) names.push(line.trim());
	}
	return names;
}

/**
 * Generate/merge the project's AGENTS.md. Conservative:
 *  - no file → create.
 *  - existing, not generated by us → merge missing sections, never delete.
 *  - existing, generated by us but differs → untouched unless force.
 *  - existing and identical → unchanged.
 */
export function writeProjectContext(cwd: string, options: { force?: boolean } = {}): InitResult {
	const path = join(cwd, PROJECT_CONTEXT_FILE);
	const summary = buildProjectSummary(cwd);
	const generated = renderProjectContext(summary);

	if (!existsSync(path)) {
		writeFileSync(path, generated, { encoding: "utf8", mode: 0o600 });
		return { status: "created", path, content: generated };
	}

	const existing = readIfExists(path) ?? "";
	if (existing.trim() === generated.trim()) {
		return { status: "unchanged", path, content: existing };
	}

	const isGenerated = existing.includes(GENERATED_HEADER);
	if (isGenerated && !options.force) {
		return {
			status: "already-generated",
			path,
			message:
				"AGENTS.md already has generated project context that differs from the re-scan. Run /init --force to regenerate.",
		};
	}

	if (isGenerated && options.force) {
		writeFileSync(path, generated, { encoding: "utf8", mode: 0o600 });
		return { status: "created", path, content: generated };
	}

	// Existing file not generated by us: merge missing sections only.
	const existingNames = sectionNames(existing);
	const missingSections = sectionNames(generated).filter((name) => !existingNames.includes(name));
	if (missingSections.length === 0) {
		return { status: "unchanged", path, content: existing };
	}
	// Extract each missing generated section (header + ## name + body until next ##).
	function extractSection(source: string, name: string): string | undefined {
		const lines = source.split("\n");
		const start = lines.findIndex((line) => line.trim() === name);
		if (start < 0) return undefined;
		let end = lines.length;
		for (let i = start + 1; i < lines.length; i++) {
			if (lines[i]!.startsWith("## ")) {
				end = i;
				break;
			}
		}
		return lines.slice(start, end).join("\n");
	}
	const additions: string[] = [];
	for (const name of missingSections) {
		const section = extractSection(generated, name);
		if (section) additions.push(section);
	}
	const merged = additions.length ? `${existing.trimEnd()}\n\n${additions.join("\n\n")}\n` : existing;
	writeFileSync(path, merged, { encoding: "utf8", mode: 0o600 });
	return { status: "merged", path, content: merged };
}

/** Ensure the cwd exists and is a directory; returns the resolved project root. */
export function ensureProjectCwd(cwd: string): { cwd: string } {
	mkdirSync(cwd, { recursive: true });
	return { cwd };
}
