import { existsSync, mkdtempSync, readFileSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { BUILTIN_SLASH_COMMANDS } from "../src/core/slash-commands.ts";
import {
	buildProjectSummary,
	PROJECT_CONTEXT_FILE,
	parseInitCommand,
	renderProjectContext,
	writeProjectContext,
} from "../src/porcupine/project-init.ts";

describe("/init project context", () => {
	function scratch(): string {
		return mkdtempSync(join(tmpdir(), "porcupine-project-init-"));
	}

	it("parses the command and its force flag", () => {
		expect(parseInitCommand("/init")).toEqual({ kind: "generate", force: false });
		expect(parseInitCommand("/init --force")).toEqual({ kind: "generate", force: true });
		expect(parseInitCommand("/init --bogus")).toEqual({ kind: "invalid", message: "Usage: /init [--force]" });
		expect(parseInitCommand("/initialize")).toBeNull();
		expect(parseInitCommand("nope")).toBeNull();
	});

	it("generates an AGENTS.md for an empty project", () => {
		const cwd = scratch();
		const result = writeProjectContext(cwd);
		expect(result.status).toBe("created");
		expect(result.path).toBe(join(cwd, PROJECT_CONTEXT_FILE));
		expect(existsSync(result.path)).toBe(true);
		const content = readFileSync(result.path, "utf8");
		expect(content).toContain("<!-- @generated by Porcupine /init");
		expect(content).toContain("## Purpose");
		expect(content).toContain("## Key Commands");
		expect(content).toContain("## Conventions");
		expect(content).toContain("## Stack");
	});

	it("scans package.json scripts and the README first lines", () => {
		const cwd = scratch();
		writeFileSync(join(cwd, "package.json"), JSON.stringify({ name: "demo", scripts: { test: "vitest run" } }));
		writeFileSync(join(cwd, "README.md"), "# Demo project\n\nA test fixture.\n");

		const result = writeProjectContext(cwd);
		expect(result.status).toBe("created");
		const content = readFileSync(result.path, "utf8");
		expect(content).toContain("Demo project");
		expect(content).toContain("`test`: `vitest run`");
		expect(content).toContain("Node.js package: `demo`");
	});

	it("does not clobber an existing user-authored AGENTS.md; merges missing sections only", () => {
		const cwd = scratch();
		writeFileSync(
			join(cwd, PROJECT_CONTEXT_FILE),
			"# AGENTS.md\n\nUser's own instructions that must survive.\n\n## Purpose\n\nBuild nice things.\n",
			"utf8",
		);
		const before = readFileSync(join(cwd, PROJECT_CONTEXT_FILE), "utf8");
		const result = writeProjectContext(cwd);
		expect(result.status).toBe("merged");
		const after = readFileSync(join(cwd, PROJECT_CONTEXT_FILE), "utf8");
		// User's own line is preserved.
		expect(after).toContain("User's own instructions that must survive.");
		// Existing Purpose section is NOT duplicated.
		expect(after.split("## Purpose")).toHaveLength(2);
		// New sections were added.
		expect(after).toContain("## Key Commands");
		expect(after).toContain("## Conventions");
		expect(after).toContain("## Stack");
		expect(after.startsWith(before)).toBe(true); // nothing deleted from the head
	});

	it("reports 'already generated' for a previous /init output that differs, unless --force", () => {
		const cwd = scratch();
		writeProjectContext(cwd);
		// Simulate drift: a generated file that no longer matches the current scan.
		writeFileSync(
			join(cwd, PROJECT_CONTEXT_FILE),
			"<!-- @generated by Porcupine /init — project context. Do not edit the header. -->\n\n# AGENTS.md\n\n## Purpose\n\nStale.\n",
			"utf8",
		);
		const denied = writeProjectContext(cwd);
		expect(denied.status).toBe("already-generated");
		expect(denied.message).toContain("/init --force");

		const forced = writeProjectContext(cwd, { force: true });
		expect(forced.status).toBe("created");
		expect(readFileSync(join(cwd, PROJECT_CONTEXT_FILE), "utf8")).toContain("## Stack");
	});

	it("is a no-op ('unchanged') when the file already matches the generated output", () => {
		const cwd = scratch();
		const first = writeProjectContext(cwd);
		expect(first.status).toBe("created");
		const second = writeProjectContext(cwd);
		expect(second.status).toBe("unchanged");
	});

	it("builds a pure summary without writing", () => {
		const cwd = scratch();
		writeFileSync(join(cwd, "package.json"), JSON.stringify({ name: "x", scripts: { build: "tsc" } }));
		const summary = buildProjectSummary(cwd);
		expect(summary.stack.join(" ")).toContain("Node.js package");
		const rendered = renderProjectContext(summary);
		expect(rendered).toContain("## Key Commands");
		expect(existsSync(join(cwd, PROJECT_CONTEXT_FILE))).toBe(false);
	});

	it("registers the command for help and autocomplete", () => {
		expect(BUILTIN_SLASH_COMMANDS).toContainEqual({
			name: "init",
			description: "Generate/merge a compact AGENTS.md project context file",
			argumentHint: "[--force]",
		});
	});
});
